#!/bin/bash

set -e
install_mastershaper()
{
#	update-rc.d ssh defaults
#	/etc/init.d/ssh start
	# Set the password so aptitude install will not prompt
	echo "mysql-server mysql-server/root_password select vitalnoc" | debconf-set-selections
	echo "mysql-server mysql-server/root_password_again select vitalnoc" | debconf-set-selections

	aptitude install php-db php-pear php5 php5-gd php5-mysql mysql-server apache2 bridge-utils vlan xtables-addons-common -y
	pear install DB_Net_IPv4

	mysqladmin -u root --password=vitalnoc create db_tshaper
	mysql --user=root --password=vitalnoc --database=mysql --execute="update user set host='%' where host='localhost';" 
	mysql --user=root --password=vitalnoc --database=mysql --execute="flush privileges;"
	aptitude update

	sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/my.cnf
	cd /tmp/remote/packages
	tar -xvf mastershaper_0.44.tar
	tar -xvf phplayersmenu-3.2.0-rc.tar
	mkdir -p /var/www/tshaper
	cp -ra MasterShaper-0.44/htdocs/* /var/www/tshaper
	mkdir -p /var/www/tshaper/jpgraph
	cp jpgraph-3.0.7.tar /var/www/tshaper/jpgraph
	cd /var/www/tshaper/jpgraph
	tar -xvf jpgraph-3.0.7.tar
	cp -ra /tmp/remote/packages/phplayersmenu-3.2.0 /var/www/tshaper
	cd /var/www/tshaper
	ln -s phplayersmenu-3.2.0/ phplayersmenu
	service apache2 restart

	service mysql restart
	chmod 777 /var/www/tshaper
	echo > /var/www/info.php
	echo "phpinfo();" >> /var/www/info.php
	echo "?>" >> /var/www/info.php

	echo "www-data ALL= NOPASSWD: /var/www/tshaper/shaper_loader.sh" >> /etc/sudoers

	cd /tmp/remote/packages
	dpkg -i linux-headers-2.6.32.27-ntcv1_2.6.32.27-ntcv1-10.00.Custom_i386.deb
	dpkg -i linux-image-2.6.32.27-ntcv1_2.6.32.27-ntcv1-10.00.Custom_i386.deb
	dpkg -i iptables_1.4.4-1_i386.deb
	update-initramfs -c -k 2.6.32.27-ntcv1
	update-initramfs -u -k 2.6.32.27-ntcv1
	update-grub
	echo "imq" >> /etc/modules
	echo "IMQ_ipt" >> /etc/modules
	echo "ipt_layer7" >> /etc/modules

	mysql -u root --password=vitalnoc --database=mysql --execute='select user,password,host from user;'
	mysql -u root --password=vitalnoc --database=mysql --execute="delete from user where user='';"
	mysql -u root --password=vitalnoc --database=mysql --execute="update user set password=PASSWORD('vitalnoc') where user='root';"
	mysql -u root --password=vitalnoc --database=mysql --execute='flush privileges;'

	echo "sort_buffer_size = 256M" > /etc/mysql/conf.d/sam.conf
	echo "read_buffer_size = 256M" >> /etc/mysql/conf.d/sam.conf
	echo "read_rnd_buffer_size = 256M" >> /etc/mysql/conf.d/sam.conf
	echo "myisam_sort_buffer_size = 256M" >> /etc/mysql/conf.d/sam.conf
	echo "max_heap_table_size= 512M" >> /etc/mysql/conf.d/sam.conf
	echo "tmp_table_size= 512M" >> /etc/mysql/conf.d/sam.conf
}

install_sam_1()
{
	src_path=/tmp/remote/packages
	GLASSFISH=glassfish-installer-v2.1.1-b31g-linux.jar
	JDK=jdk-6u26-linux-i586.bin
	CONNECTOR=mysql-connector-java-5.1.10-bin.jar
	jdk_path=/usr/lib/jvm
	glassfish_path=/opt
	SERVICE=/etc/init.d/glassfish

	aptitude install update-alternatives -y
	 
	### Instalar Java JDK ###
	mkdir -p $jdk_path
	mv $src_path/$JDK $jdk_path
	cd $jdk_path
	chmod 755 $JDK  
	
	#press enter to continue
	echo | sh $JDK
	echo "JDK Installed succesfull"
	
	update-alternatives --install "/usr/bin/java" "java" "/usr/lib/jvm/jdk1.6.0_26/bin/java" 1 
	update-alternatives --install "/usr/bin/javac" "javac" "/usr/lib/jvm/jdk1.6.0_26/bin/javac" 1
	update-alternatives --install "/usr/bin/javah" "javah" "/usr/lib/jvm/jdk1.6.0_26/bin/javah" 1
	update-alternatives --install "/usr/bin/javaws" "javaws" "/usr/lib/jvm/jdk1.6.0_26/bin/javaws" 1

	## setear variables ####
	echo "JAVA_HOME=/usr/lib/jvm/jdk1.6.0_26" >> /root/.profile
	echo 'PATH=$JAVA_HOME/bin:$PATH' >> /root/.profile
	java -version
	 
	mv $src_path/$GLASSFISH $glassfish_path
	cd $glassfish_path
	# Must accept gpl - echo 'a'
	echo 'a' | java -Xmx256m -jar $GLASSFISH
	cd glassfish; chmod -R +x lib/ant/bin
	lib/ant/bin/ant -f setup.xml
	
	echo "Glassfish Installed succesfull"
	
	cp $src_path/$CONNECTOR $glassfish_path/glassfish/lib/
	echo "Mysql Connector Installed succesfull"
	
	### crear servicio ####
	 
	echo "#!/bin/bash" > $SERVICE
	echo " " >> $SERVICE
	echo "GLASSFISH=/opt/glassfish/bin" >> $SERVICE
	echo " " >> $SERVICE
	echo 'case "$1" in' >> $SERVICE
	echo "start)" >> $SERVICE
	echo 'echo "Starting glassfish.."' >> $SERVICE
	echo '$GLASSFISH/asadmin start-domain domain1 &' >> $SERVICE
	echo ";;" >> $SERVICE
	echo "stop)" >> $SERVICE
	echo 'echo "Stopping glassfish.."' >> $SERVICE
	echo '$GLASSFISH/asadmin stop-domain domain1 &' >> $SERVICE
	echo ";;" >> $SERVICE
	echo "restart)" >> $SERVICE
	echo '$0 stop' >> $SERVICE
	echo '$0 start' >> $SERVICE
	echo ";;" >> $SERVICE
	echo "*)" >> $SERVICE
	echo " " $SERVICE
	echo 'echo "Usage: $0 {start|stop|restart}"' >> $SERVICE
	echo "exit 1" >> $SERVICE
	echo ";;" >>$SERVICE
	echo "esac" >>$SERVICE
	echo ":" >>$SERVICE

	chmod 755 $SERVICE

	### Crear link inicio automatico ###
	update-rc.d glassfish defaults

	### Borrar archivos ###
	mv $jdk_path/$JDK $src_path	
	mv $glassfish_path/$GLASSFISH $src_path
	service glassfish start

}
	 
install_sam_2()
{
	src_path=/tmp/remote/packages
	GLASSFISH=$src_path/glassfish-installer-v2.1.1-b31g-linux.jar
	MYSQLC=$src_path/mysql-connector-java-5.1.10-bin.jar
	INFOBRIGHT=$src_path/infobright-4.0.6-0-i686-ice.deb
	JDK=$src_path/jdk-6u26-linux-i586.bin
	SERVICE=/etc/init.d/glassfish
	CAP_VERSION=8
	CAPTURA=$src_path/capV${CAP_VERSION}.tar
	NSCD=$src_path/nscd_2.11.1-0ubuntu7.11_i386.deb
	SRS_VERSION=3
	SRS=$src_path/srs${SRS_VERSION}.tar
	 
	### Install INfobright ####

	apt-get install -y build-essential
	dpkg -i $NSCD
	sed -i '65s/no/yes/' /etc/nscd.conf
	service nscd restart
	chmod 755 $INFOBRIGHT
	dpkg -i $INFOBRIGHT
	cd /usr/local/infobright ; echo -e "n\nn\nn\ny\n3300\ny\n" | ./postconfig.sh
	
	### Inciar servidor infobright###
	 
	sed -i '41i skip-host-cache' /etc/my-ib.cnf
	sed -i '42i skip-name-resolve' /etc/my-ib.cnf
	sed -i '43i bind-address=0.0.0.0' /etc/my-ib.cnf
	/etc/init.d/mysqld-ib start
	 
	/etc/init.d/mysqld-ib restart
	mysql-ib -u root --database=mysql --execute='update user set host="%" where host="localhost";'
	mysql-ib -u root --database=mysql --execute='update user set password=PASSWORD("vitalnoc");'
	mysql-ib -u root --database=mysql --execute='flush privileges;'
	
	## conector -mysql ####
	cp $MYSQLC /opt/glassfish/lib

	# Captura
	cd /opt
	tar xpf $CAPTURA
	cp /opt/capV${CAP_VERSION}/lib/*jnetpcap* /usr/lib/
	cp /opt/capV${CAP_VERSION}/lib/*jnetpcap* /usr/lib/jvm/jdk1.6.0_26/jre/lib/i386/
	cp /opt/capV${CAP_VERSION}/lib/*jnetpcap* /usr/share/java/
	mkdir /media/capturas/
	mount -t tmpfs -o size=256M tmpfs /media/capturas/
	sed -i '14i mkdir /media/capturas/' /etc/rc.local.orig
	sed -i '15i mount -t tmpfs -o size=256M tmpfs /media/capturas/' /etc/rc.local.orig
	sed -i 's/captura.ruta.file2load=.*$/captura.ruta.file2load=\/media\/capturas\//g' /opt/capV${CAP_VERSION}/configuration/configuration.properties
	sed -i 's/captura.folder=.*$/captura.folder=\/media\/capturas\//g' /opt/capV${CAP_VERSION}/configuration/configuration.properties

	# SRS
	cd /opt
	tar xpf $SRS
	sed -i "s/ubuntu/${PRODUCT_CODE}/g" /opt/srs${SRS_VERSION}/configuration/jndi.properties
}

install_ssn()
{
#general
HOSTNAME=`hostname`
PROJECT_NAME="automatic"
GLASSFISH_HOME="/opt/glassfish/bin/"
DATABASE_NAME="ssn_"$PROJECT_NAME 
PATH_EAR="/tmp/remote/packages/ssn3.1.ear"
SERVER_DATABASE=$HOSTNAME
USER_DATABASE="root"
PASSWORD_DATABASE="vitalnoc"
DATABASE_PORT=3306

#collector
COLLECTOR_IP="127.0.0.1"
COLLECTOR_HOSTNAME=$HOSTNAME

####################################################################
#creating database 
####################################################################

#change mysql by mysql-ib ***************
echo "creating database"
mysql -h $SERVER_DATABASE -u$USER_DATABASE -p$PASSWORD_DATABASE <<EOF
CREATE DATABASE IF NOT EXISTS $DATABASE_NAME;
USE $DATABASE_NAME;

#table categories
CREATE TABLE categories (categorie_id bigint(20) NOT NULL AUTO_INCREMENT,  categorie_active int(11) DEFAULT NULL,  categorie_name varchar(255) DEFAULT NULL,  categorie_order int(2) DEFAULT NULL,  PRIMARY KEY (categorie_id)) ENGINE=MyISAM AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;

#data for table categories
truncate table categories;
INSERT INTO categories (categorie_active, categorie_name, categorie_order) VALUES ('1', 'Bandwidth', '1');
INSERT INTO categories (categorie_active, categorie_name, categorie_order) VALUES ('1', 'Protocols', '2');
INSERT INTO categories (categorie_active, categorie_name, categorie_order) VALUES ('1', 'Host', '3');
INSERT INTO categories (categorie_active, categorie_name, categorie_order) VALUES ('1', 'Conversations', '4');
INSERT INTO categories (categorie_active, categorie_name, categorie_order) VALUES ('1', 'Web', '5');
INSERT INTO categories (categorie_active, categorie_name, categorie_order) VALUES ('1', 'QoS', '6');
INSERT INTO categories (categorie_active, categorie_name, categorie_order) VALUES ('1', 'Ports', '7');

#table subcategories
CREATE TABLE subcategories (subcategorie_id BIGINT(20) NOT NULL AUTO_INCREMENT, subcategorie_active INT(11) DEFAULT NULL, subcategorie_name VARCHAR(255) DEFAULT NULL,  subcategorie_categorie_id BIGINT(20) DEFAULT NULL,  subcategorie_order INT(2) DEFAULT NULL,  PRIMARY KEY (subcategorie_id)) ENGINE=MYISAM AUTO_INCREMENT=24 DEFAULT CHARSET=latin1;

#data for table subcategories            
INSERT INTO subcategories (subcategorie_active, subcategorie_name, subcategorie_categorie_id, subcategorie_order) VALUES ('1', 'Bandwidth Over Time Bits', '1', '1');
INSERT INTO subcategories (subcategorie_active, subcategorie_name, subcategorie_categorie_id, subcategorie_order) VALUES ('1', 'Bandwidth Over Time Bytes', '1', '2');
INSERT INTO subcategories (subcategorie_active, subcategorie_name, subcategorie_categorie_id, subcategorie_order) VALUES ('1', 'Bandwidth Over Time Source Bits', '1', '3');
INSERT INTO subcategories (subcategorie_active, subcategorie_name, subcategorie_categorie_id, subcategorie_order) VALUES ('1', 'Bandwidth Over Time Destination Bits', '1', '4');
INSERT INTO subcategories (subcategorie_active, subcategorie_name, subcategorie_categorie_id, subcategorie_order) VALUES ('1', 'Bandwidth Over Time Source and Destination Bits', '1', '5');
INSERT INTO subcategories (subcategorie_active, subcategorie_name, subcategorie_categorie_id, subcategorie_order) VALUES ('0', 'Bandwidth Over Time Bits Live', '1', '6');
INSERT INTO subcategories (subcategorie_active, subcategorie_name, subcategorie_categorie_id, subcategorie_order) VALUES ('1', 'Network Protocols', '2', '1');
INSERT INTO subcategories (subcategorie_active, subcategorie_name, subcategorie_categorie_id, subcategorie_order) VALUES ('1', 'IP Protocols', '2', '2');
INSERT INTO subcategories (subcategorie_active, subcategorie_name, subcategorie_categorie_id, subcategorie_order) VALUES ('1', 'TCP Protocols', '2', '3');
INSERT INTO subcategories (subcategorie_active, subcategorie_name, subcategorie_categorie_id, subcategorie_order) VALUES ('1', 'UDP Protocols', '2', '4');
INSERT INTO subcategories (subcategorie_active, subcategorie_name, subcategorie_categorie_id, subcategorie_order) VALUES ('1', 'IP Talkers Bytes', '3', '1');
INSERT INTO subcategories (subcategorie_active, subcategorie_name, subcategorie_categorie_id, subcategorie_order) VALUES ('1', 'IP Talkers Destinations Bytes', '3', '2');
INSERT INTO subcategories (subcategorie_active, subcategorie_name, subcategorie_categorie_id, subcategorie_order) VALUES ('1', 'IP Talkers Sources Bytes', '3', '3');
INSERT INTO subcategories (subcategorie_active, subcategorie_name, subcategorie_categorie_id, subcategorie_order) VALUES ('1', 'Hostname Talkers Bytes', '3', '4');
INSERT INTO subcategories (subcategorie_active, subcategorie_name, subcategorie_categorie_id, subcategorie_order) VALUES ('1', 'Hostname Talkers Destinations Bytes', '3', '5');
INSERT INTO subcategories (subcategorie_active, subcategorie_name, subcategorie_categorie_id, subcategorie_order) VALUES ('1', 'Hostname Talkers Sources Bytes', '3', '6');            
INSERT INTO subcategories (subcategorie_active, subcategorie_name, subcategorie_categorie_id, subcategorie_order) VALUES ('1', 'Host Conversations Bytes', '4', '1');
INSERT INTO subcategories (subcategorie_active, subcategorie_name, subcategorie_categorie_id, subcategorie_order) VALUES ('1', 'Host TCP Conversations Bytes', '4', '2');
INSERT INTO subcategories (subcategorie_active, subcategorie_name, subcategorie_categorie_id, subcategorie_order) VALUES ('1', 'Host UDP Conversations Bytes', '4', '3');
INSERT INTO subcategories (subcategorie_active, subcategorie_name, subcategorie_categorie_id, subcategorie_order) VALUES ('1', 'Web Server Hosts', '5', '1');
INSERT INTO subcategories (subcategorie_active, subcategorie_name, subcategorie_categorie_id, subcategorie_order) VALUES ('1', 'Type of Service', '6', '1');
INSERT INTO subcategories (subcategorie_active, subcategorie_name, subcategorie_categorie_id, subcategorie_order) VALUES ('1', 'Top Ports', '7', '1');
INSERT INTO subcategories (subcategorie_active, subcategorie_name, subcategorie_categorie_id, subcategorie_order) VALUES ('1', 'TCP Ports', '7', '2');
INSERT INTO subcategories (subcategorie_active, subcategorie_name, subcategorie_categorie_id, subcategorie_order) VALUES ('1', 'UDP Ports', '7', '3');

#table collectors
CREATE TABLE collectors (collector_id bigint(20) NOT NULL AUTO_INCREMENT, collector_type int(1) DEFAULT NULL COMMENT '1 openblocks 2 server', collector_host varchar(50) DEFAULT NULL, collector_ip varchar(15)DEFAULT NULL, collector_site varchar(100) DEFAULT NULL, collector_description varchar(150) DEFAULT NULL, collector_port int(5) DEFAULT NULL, collector_port_connection_server int(5) DEFAULT NULL,   collector_is_active int(1) DEFAULT NULL COMMENT '1 active 0 no active', collector_context varchar(25) DEFAULT NULL COMMENT 'part of url', collector_date_register timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'date of register', PRIMARY KEY (collector_id)) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

#data for collectors
INSERT INTO collectors (collector_type, collector_host, collector_ip, collector_is_active) VALUES ('2', '$COLLECTOR_HOSTNAME', '$COLLECTOR_IP', '1');

#table configuration            
CREATE TABLE configuration (id_configuration bigint(20) NOT NULL AUTO_INCREMENT,help_path varchar(255) DEFAULT NULL,jws_path varchar(255) DEFAULT NULL,jms_time_wait_connectivity int(11) DEFAULT NULL, jms_time_wait_message int(11) DEFAULT NULL,project_name varchar(255) DEFAULT NULL,seconds_live varchar(20) DEFAULT NULL,used_master_shaper varchar(3) DEFAULT NULL,master_shaper_server varchar(20) DEFAULT NULL, PRIMARY KEY (id_configuration)) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

#data for table configuration
truncate table configuration;
INSERT INTO configuration (jws_path, help_path, project_name, jms_time_wait_message, jms_time_wait_connectivity,seconds_live, used_master_shaper) VALUES ('http://localhost:8080/ssn-war/help','http://localhost:8080/ssn-war/help', '$PROJECT_NAME', '10000', '10000','20', 'no');

#table users
CREATE TABLE users (user_id bigint(20) NOT NULL AUTO_INCREMENT,user_name varchar(50) DEFAULT NULL,user_password varchar(50) DEFAULT NULL,user_level int(1) DEFAULT NULL COMMENT '1 =admin 2 = guest',  user_description varchar(100) DEFAULT NULL, PRIMARY KEY (user_id)) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

#data for table users
insert  into users(user_id,user_name,user_password,user_level,user_description) values (1,'skuarch','123',1,'administrator');
insert  into users(user_id,user_name,user_password,user_level,user_description) values (2,'julio','123',1,'administrator');
insert  into users(user_id,user_name,user_password,user_level,user_description) values (3,'invitado','123',2,'guest');
EOF

echo "database was created successfully"

####################################################################
#glassfish configuration
####################################################################
cd $GLASSFISH_HOME
./asadmin set server-config.jms-service.jms-host.default_JMS_host.host="$COLLECTOR_HOSTNAME"
./asadmin set server.iiop-service.iiop-listener.orb-listener-1.address="$COLLECTOR_HOSTNAME"


####################################################################
#deploying .ear in glassfish
####################################################################
./asadmin deploy $PATH_EAR

./asadmin create-jdbc-connection-pool --user admin --datasourceclassname com.mysql.jdbc.jdbc2.optional.MysqlDataSource --restype javax.sql.DataSource --property user=$USER_DATABASE:password=$PASSWORD_DATABASE:DatabaseName=$DATABASE_NAME:ServerName=$SERVER_DATABASE:port=$DATABASE_PORT connection_pool_ssn_3_1

./asadmin create-jdbc-resource --user admin --connectionpoolid connection_pool_ssn_3_1 jdbc/ssn_3_1

./asadmin create-jms-resource --restype=javax.jms.TopicConnectionFactory jms_connection_factory_ssn_3_1

./asadmin create-jms-resource --restype=javax.jms.Topic jms_topic_ssn_3_1

#restart glassfish
./asadmin stop-domain
./asadmin start-domain

	cd /opt/srs${SRS_VERSION}
	java -jar srs3.1.jar
}

install_mastershaper
install_sam_1
install_sam_2
install_ssn

exit 0
